#!/bin/sh

# Run to start the whole system up, 5 services (one is nginx)
# `./run``
# Or, run with a parameter service name (from docker-compose) to restart just that service
# `./run meminator`

if [ -f .env ]; then
  echo "Sourcing .env file"
  set -o allexport
  source .env
  set +o allexport
else
  echo ".env file not found! Please ensure the .env file is present in the current directory."
  exit 1
fi

if ! docker compose up --build -d "$@"; then
  echo ""
  echo "Failed to build or start services!"
  exit 1
fi

# Check if running in GitHub Codespaces
if [ -n "$CODESPACES" ]; then
  echo "Running in GitHub Codespaces."

  APP_PORT=10114

  URL="https://${CODESPACE_NAME}-${APP_PORT}.app.github.dev"

# Check if running in Gitpod
elif [ -n "$GITPOD_INSTANCE_ID" ]; then
  echo "Running in Gitpod."

  # Get the workspace url
  URL=$(gp url 10114)

else
  # Default to local environment
  echo "Running locally."
  source .env
  URL="http://localhost:10114/"

fi

echo "Meminator running on port 10114 at: $URL"
